version: '3.8'

services:

  barsic-web:
    container_name: barsic-web
    hostname: barsic-web
    build: .
    environment:
      DEBUG: ${DEBUG}
      PROJECT_NAME: ${PROJECT_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # AppSettings
      MSSQL_DRIVER_TYPE: ${MSSQL_DRIVER_TYPE}
      MSSQL_SERVER: ${MSSQL_SERVER}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PWD: ${MSSQL_PWD}
      MSSQL_DATABASE1: ${MSSQL_DATABASE1}
      MSSQL_DATABASE2: ${MSSQL_DATABASE2}
      MSSQL_DATABASE_BITRIX: ${MSSQL_DATABASE_BITRIX}
      MSSQL_SERVER_RK: ${MSSQL_SERVER_RK}
      MSSQL_USER_RK: ${MSSQL_USER_RK}
      MSSQL_PWD_RK: ${MSSQL_PWD_RK}
      MSSQL_DATABASE_RK: ${MSSQL_DATABASE_RK}
      REPORT_XML: ${REPORT_XML}
      AGENT_XML: ${AGENT_XML}
      TOTAL_REPORT_XML: ${TOTAL_REPORT_XML}
      LOCAL_FOLDER: ${LOCAL_FOLDER}
      PATH: ${PATH}
      CREDENTIALS_FILE: ${CREDENTIALS_FILE}
      LIST_GOOGLE_DOCS: ${LIST_GOOGLE_DOCS}
      YADISK_TOKEN: ${YADISK_TOKEN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHANEL_ID: ${TELEGRAM_CHANEL_ID}
      TELEGRAM_PROXY_USE: ${TELEGRAM_PROXY_USE}
      TELEGRAM_PROXY_TYPE: ${TELEGRAM_PROXY_TYPE}
      TELEGRAM_PROXY_IP: ${TELEGRAM_PROXY_IP}
      TELEGRAM_PROXY_PORT: ${TELEGRAM_PROXY_PORT}
      TELEGRAM_PROXY_AUTH: ${TELEGRAM_PROXY_AUTH}
      TELEGRAM_PROXY_USERNAME: ${TELEGRAM_PROXY_USERNAME}
      TELEGRAM_PROXY_PASSWORD: ${TELEGRAM_PROXY_PASSWORD}
      GOOGLE_ALL_READ: ${GOOGLE_ALL_READ}
      GOOGLE_READER_LIST: ${GOOGLE_READER_LIST}
      GOOGLE_WRITER_LIST: ${GOOGLE_WRITER_LIST}
    networks:
      - network
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt/app/
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.2
    networks:
      - network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - barsic_pg:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2-rc1
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    volumes:
      - barsic_redis:/data
    ports:
      - "6379:6379"
    networks:
      - network

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.25
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/configs:/etc/nginx/conf.d
    depends_on:
      - barsic-web
    ports:
      - "80:80"
    networks:
      - network

volumes:
  barsic_pg:
  barsic_redis:

networks:
  network: