[tool.poetry]
name = "barsic-web"
version = "0.1.0"
description = ""
authors = ["Ivan Bazhenov <iv.bazhenov@vk.team>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
