"""init

Revision ID: 070523e07d59
Revises: 8e0da5a11723
Create Date: 2024-02-28 18:16:21.076467

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "070523e07d59"
down_revision = "8e0da5a11723"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report_cache", sa.Column("report_date", sa.DATE(), nullable=False))
    op.drop_constraint("unique_report", "report_cache", type_="unique")
    op.create_unique_constraint(
        "unique_report", "report_cache", ["report_date", "report_type"]
    )
    op.drop_column("report_cache", "_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_cache",
        sa.Column("_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("unique_report", "report_cache", type_="unique")
    op.create_unique_constraint(
        "unique_report", "report_cache", ["_date", "report_type"]
    )
    op.drop_column("report_cache", "report_date")
    # ### end Alembic commands ###
