"""init

Revision ID: 257859d54620
Revises: b5099e79af78
Create Date: 2024-02-24 13:47:37.281844

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "257859d54620"
down_revision = "b5099e79af78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("report_element_title_key", "report_element", type_="unique")
    op.create_unique_constraint(
        "unique_title_elements", "report_element", ["title", "group_id"]
    )
    op.drop_constraint("unique_title", "report_group", type_="unique")
    op.create_unique_constraint(
        "unique_title_groups", "report_group", ["title", "report_name_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_title_groups", "report_group", type_="unique")
    op.create_unique_constraint(
        "unique_title", "report_group", ["title", "report_name_id"]
    )
    op.drop_constraint("unique_title_elements", "report_element", type_="unique")
    op.create_unique_constraint("report_element_title_key", "report_element", ["title"])
    # ### end Alembic commands ###
