"""init

Revision ID: 2ffc1af2d2c2
Revises: 070523e07d59
Create Date: 2024-02-28 18:18:10.345150

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "2ffc1af2d2c2"
down_revision = "070523e07d59"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
