"""init

Revision ID: 5d5fb5d75513
Revises: cba87c2c864c
Create Date: 2024-02-24 13:33:39.367749

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "5d5fb5d75513"
down_revision = "cba87c2c864c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "report_element", ["id"])
    op.drop_constraint("report_group_title_key", "report_group", type_="unique")
    op.create_unique_constraint(None, "report_group", ["id"])
    op.create_unique_constraint(None, "report_name", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "report_name", type_="unique")
    op.drop_constraint(None, "report_group", type_="unique")
    op.create_unique_constraint("report_group_title_key", "report_group", ["title"])
    op.drop_constraint(None, "report_element", type_="unique")
    # ### end Alembic commands ###
