"""add_google_report_id_model

Revision ID: 6fc88f24054f
Revises: 257859d54620
Create Date: 2024-02-24 14:43:48.887716

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "6fc88f24054f"
down_revision = "257859d54620"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_report_ids",
        sa.Column("month", sa.String(length=255), nullable=False),
        sa.Column("doc_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("month"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("google_report_ids")
    # ### end Alembic commands ###
