"""init

Revision ID: 8e0da5a11723
Revises: fe92ba674a75
Create Date: 2024-02-28 18:09:22.629837

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "8e0da5a11723"
down_revision = "fe92ba674a75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report_cache", sa.Column("_date", sa.DATE(), nullable=False))
    op.drop_constraint("unique_report", "report_cache", type_="unique")
    op.create_unique_constraint(
        "unique_report", "report_cache", ["_date", "report_type"]
    )
    op.create_unique_constraint(None, "report_cache", ["id"])
    op.drop_column("report_cache", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_cache",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "report_cache", type_="unique")
    op.drop_constraint("unique_report", "report_cache", type_="unique")
    op.create_unique_constraint(
        "unique_report", "report_cache", ["date", "report_type"]
    )
    op.drop_column("report_cache", "_date")
    # ### end Alembic commands ###
